export const Columns =[
    {
        Header:'Id',
        accessor:'id'
    },
    {
        Header:'Title',
        accessor:'title'
    },
    {
        Header:'User',
        accessor:'username'
    },
    {
        Header:'Email',
        accessor:'email'
    },
    {
        Header:'Mobile',
        accessor:'mobile_number'
    },
    {
        Header:'Goal',
        accessor:'goal_amount'
    },
    {
        Header:'Funds Raised',
        accessor:'fund_raised'
    },
    {
        Header:'Status',
        accessor:'status'
    },
    {
        Header:'Date',
        accessor:'end_date'
    },
    {
        Header:'Deadline',
        accessor:'end_date'
    },
    {
        Header:'Actions',
    },
]